/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeIndexRouteImport } from './routes/resume/index'
import { Route as ResumeLangIndexRouteImport } from './routes/resume/$lang/index'
import { Route as ResumeLangPageRouteImport } from './routes/resume/$lang/$page'
import { Route as ResumeApiResumeChatRouteImport } from './routes/resume/api/resume-chat'

const ResumeIndexRoute = ResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangIndexRoute = ResumeLangIndexRouteImport.update({
  id: '/resume/$lang/',
  path: '/resume/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangPageRoute = ResumeLangPageRouteImport.update({
  id: '/resume/$lang/$page',
  path: '/resume/$lang/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeApiResumeChatRoute = ResumeApiResumeChatRouteImport.update({
  id: '/resume/api/resume-chat',
  path: '/resume/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/resume/': typeof ResumeIndexRoute
  '/resume/$lang/$page': typeof ResumeLangPageRoute
  '/resume/api/resume-chat': typeof ResumeApiResumeChatRoute
  '/resume/$lang/': typeof ResumeLangIndexRoute
}
export interface FileRoutesByTo {
  '/resume': typeof ResumeIndexRoute
  '/resume/$lang/$page': typeof ResumeLangPageRoute
  '/resume/api/resume-chat': typeof ResumeApiResumeChatRoute
  '/resume/$lang': typeof ResumeLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/resume/': typeof ResumeIndexRoute
  '/resume/$lang/$page': typeof ResumeLangPageRoute
  '/resume/api/resume-chat': typeof ResumeApiResumeChatRoute
  '/resume/$lang/': typeof ResumeLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/resume/'
    | '/resume/$lang/$page'
    | '/resume/api/resume-chat'
    | '/resume/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/resume'
    | '/resume/$lang/$page'
    | '/resume/api/resume-chat'
    | '/resume/$lang'
  id:
    | '__root__'
    | '/resume/'
    | '/resume/$lang/$page'
    | '/resume/api/resume-chat'
    | '/resume/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ResumeIndexRoute: typeof ResumeIndexRoute
  ResumeLangPageRoute: typeof ResumeLangPageRoute
  ResumeApiResumeChatRoute: typeof ResumeApiResumeChatRoute
  ResumeLangIndexRoute: typeof ResumeLangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume/': {
      id: '/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof ResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/': {
      id: '/resume/$lang/'
      path: '/resume/$lang'
      fullPath: '/resume/$lang/'
      preLoaderRoute: typeof ResumeLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/$page': {
      id: '/resume/$lang/$page'
      path: '/resume/$lang/$page'
      fullPath: '/resume/$lang/$page'
      preLoaderRoute: typeof ResumeLangPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/api/resume-chat': {
      id: '/resume/api/resume-chat'
      path: '/resume/api/resume-chat'
      fullPath: '/resume/api/resume-chat'
      preLoaderRoute: typeof ResumeApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ResumeIndexRoute: ResumeIndexRoute,
  ResumeLangPageRoute: ResumeLangPageRoute,
  ResumeApiResumeChatRoute: ResumeApiResumeChatRoute,
  ResumeLangIndexRoute: ResumeLangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
