/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeIndexRouteImport } from './routes/resume/index'
import { Route as ResumeLangIndexRouteImport } from './routes/resume/$lang/index'
import { Route as ResumeLangProfileRouteImport } from './routes/resume/$lang/$profile'
import { Route as ResumeLangAboutRouteImport } from './routes/resume/$lang/about'
import { Route as ResumeLangContactRouteImport } from './routes/resume/$lang/contact'
import { Route as ResumeLangServicesRouteImport } from './routes/resume/$lang/services'
import { Route as ResumeLangShopRouteImport } from './routes/resume/$lang/shop'
import { Route as ResumeApiResumeChatRouteImport } from './routes/resume/api/resume-chat'

const ResumeIndexRoute = ResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangIndexRoute = ResumeLangIndexRouteImport.update({
  id: '/resume/$lang/',
  path: '/resume/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangProfileRoute = ResumeLangProfileRouteImport.update({
  id: '/resume/$lang/$profile',
  path: '/resume/$lang/$profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangAboutRoute = ResumeLangAboutRouteImport.update({
  id: '/resume/$lang/about',
  path: '/resume/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangContactRoute = ResumeLangContactRouteImport.update({
  id: '/resume/$lang/contact',
  path: '/resume/$lang/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangServicesRoute = ResumeLangServicesRouteImport.update({
  id: '/resume/$lang/services',
  path: '/resume/$lang/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLangShopRoute = ResumeLangShopRouteImport.update({
  id: '/resume/$lang/shop',
  path: '/resume/$lang/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeApiResumeChatRoute = ResumeApiResumeChatRouteImport.update({
  id: '/resume/api/resume-chat',
  path: '/resume/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/resume/': typeof ResumeIndexRoute
  '/resume/$lang/$profile': typeof ResumeLangProfileRoute
  '/resume/$lang/about': typeof ResumeLangAboutRoute
  '/resume/$lang/contact': typeof ResumeLangContactRoute
  '/resume/$lang/services': typeof ResumeLangServicesRoute
  '/resume/$lang/shop': typeof ResumeLangShopRoute
  '/resume/api/resume-chat': typeof ResumeApiResumeChatRoute
  '/resume/$lang/': typeof ResumeLangIndexRoute
}
export interface FileRoutesByTo {
  '/resume': typeof ResumeIndexRoute
  '/resume/$lang/$profile': typeof ResumeLangProfileRoute
  '/resume/$lang/about': typeof ResumeLangAboutRoute
  '/resume/$lang/contact': typeof ResumeLangContactRoute
  '/resume/$lang/services': typeof ResumeLangServicesRoute
  '/resume/$lang/shop': typeof ResumeLangShopRoute
  '/resume/api/resume-chat': typeof ResumeApiResumeChatRoute
  '/resume/$lang': typeof ResumeLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/resume/': typeof ResumeIndexRoute
  '/resume/$lang/$profile': typeof ResumeLangProfileRoute
  '/resume/$lang/about': typeof ResumeLangAboutRoute
  '/resume/$lang/contact': typeof ResumeLangContactRoute
  '/resume/$lang/services': typeof ResumeLangServicesRoute
  '/resume/$lang/shop': typeof ResumeLangShopRoute
  '/resume/api/resume-chat': typeof ResumeApiResumeChatRoute
  '/resume/$lang/': typeof ResumeLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/resume/'
    | '/resume/$lang/$profile'
    | '/resume/$lang/about'
    | '/resume/$lang/contact'
    | '/resume/$lang/services'
    | '/resume/$lang/shop'
    | '/resume/api/resume-chat'
    | '/resume/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/resume'
    | '/resume/$lang/$profile'
    | '/resume/$lang/about'
    | '/resume/$lang/contact'
    | '/resume/$lang/services'
    | '/resume/$lang/shop'
    | '/resume/api/resume-chat'
    | '/resume/$lang'
  id:
    | '__root__'
    | '/resume/'
    | '/resume/$lang/$profile'
    | '/resume/$lang/about'
    | '/resume/$lang/contact'
    | '/resume/$lang/services'
    | '/resume/$lang/shop'
    | '/resume/api/resume-chat'
    | '/resume/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ResumeIndexRoute: typeof ResumeIndexRoute
  ResumeLangProfileRoute: typeof ResumeLangProfileRoute
  ResumeLangAboutRoute: typeof ResumeLangAboutRoute
  ResumeLangContactRoute: typeof ResumeLangContactRoute
  ResumeLangServicesRoute: typeof ResumeLangServicesRoute
  ResumeLangShopRoute: typeof ResumeLangShopRoute
  ResumeApiResumeChatRoute: typeof ResumeApiResumeChatRoute
  ResumeLangIndexRoute: typeof ResumeLangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume/': {
      id: '/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof ResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/': {
      id: '/resume/$lang/'
      path: '/resume/$lang'
      fullPath: '/resume/$lang/'
      preLoaderRoute: typeof ResumeLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/$profile': {
      id: '/resume/$lang/$profile'
      path: '/resume/$lang/$profile'
      fullPath: '/resume/$lang/$profile'
      preLoaderRoute: typeof ResumeLangProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/about': {
      id: '/resume/$lang/about'
      path: '/resume/$lang/about'
      fullPath: '/resume/$lang/about'
      preLoaderRoute: typeof ResumeLangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/contact': {
      id: '/resume/$lang/contact'
      path: '/resume/$lang/contact'
      fullPath: '/resume/$lang/contact'
      preLoaderRoute: typeof ResumeLangContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/services': {
      id: '/resume/$lang/services'
      path: '/resume/$lang/services'
      fullPath: '/resume/$lang/services'
      preLoaderRoute: typeof ResumeLangServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$lang/shop': {
      id: '/resume/$lang/shop'
      path: '/resume/$lang/shop'
      fullPath: '/resume/$lang/shop'
      preLoaderRoute: typeof ResumeLangShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/api/resume-chat': {
      id: '/resume/api/resume-chat'
      path: '/resume/api/resume-chat'
      fullPath: '/resume/api/resume-chat'
      preLoaderRoute: typeof ResumeApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ResumeIndexRoute: ResumeIndexRoute,
  ResumeLangProfileRoute: ResumeLangProfileRoute,
  ResumeLangAboutRoute: ResumeLangAboutRoute,
  ResumeLangContactRoute: ResumeLangContactRoute,
  ResumeLangServicesRoute: ResumeLangServicesRoute,
  ResumeLangShopRoute: ResumeLangShopRoute,
  ResumeApiResumeChatRoute: ResumeApiResumeChatRoute,
  ResumeLangIndexRoute: ResumeLangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
